### PR TITLE
Use CRON to manage staging

### PR DESCRIPTION
**Pull request by wlandau**
@shikokuchuo, this PR uses CRON expressions to schedule when staging updates and when it resets. I think this is a lot simpler, easier to maintain, and more transparent than the awkward `multiverse.internals::staging_is_active()`.

### CODE REVIEW

**Comment by wlandau** [comment]
I used https://crontab.cronhub.io/ to check the CRON expressions. Not every month has the full date range 15-31, but ChatGPT seems to think CRON will harmlessly ignore days not in a particular month.

**Review by shikokuchuo — CHANGES_REQUESTED** [review]
Very nice! I might be missing something, but we don't need it to reset *every* hour in the month prior to staging?

Also I noticed that these are on Mac runners - I think we can switch these to Ubuntu-latest? I remember you asking this question before.

**Comment by shikokuchuo** [comment]
I've updated the reset to once a day during the reset period. 

As it's less error-prone than trying to do this only once, and in case we want to add more logic at a later date.

We can have the type of runners discussion elsewhere.

I'll go ahead and merge this PR first.

**Comment by wlandau** [comment]
Thanks! And I completely agree about `ubuntu-latest` for `reset.yaml`, c.f. https://github.com/r-multiverse/staging/pull/4

**Pull request merged**
